### ISSUE TITLE
org.rdfhdt.hdt.trans is not defined

### ISSUE THREAD

**Issue by flamingofugang** [rdfhdt/hdt-mr#1]
Hi, 

When I built it using maven, I cannot find org.rdfhdt.hdt.trans package in the git repository, but it is required by two files:

```
[fug2@cbbdev11 hdt-java]$ grep -r 'org.rdfhdt.hdt.trans' .
./hdt-mr/src/main/java/org/rdfhdt/hdt/dictionary/impl/section/**TransientDictionarySection.java**:import org.rdfhdt.hdt.trans.TransientElement;
./hdt-mr/src/main/java/org/rdfhdt/mrbuilder/**HDTBuilderDriver**.java:import org.rdfhdt.hdt.trans.TransientElement;
```

Any idea about where I can find the package?

Best,
Gang

**Comment by artob** [comment]
I've confirmed that the source code for `org.rdfhdt.hdt.trans.TransientElement` is indeed missing from the [ZIP file](http://dataweb.infor.uva.es/projects/hdt-mr/code/HDT-MR_alpha.zip) published with the [HDT-MR paper](http://dataweb.infor.uva.es/projects/hdt-mr/), which means that the source code as published isn't in fact buildable or usable.

**Comment by artob** [comment]
Pinging @jm-gimenez-garcia, @migumar2, and @webdata. Would one of you have a copy of the missing source code file(s)?

**Comment by jm-gimenez-garcia** [comment]
I uploaded the file. Thank you for the catch.

**Comment by flamingofugang** [comment]
Thank you very much, it is working now. I also added the pom file to compile codes easily.
